export const DUMMY_LEADERBOARD = [
  {
    user: {
      full_name: "James Gomez",
      highschool: "Group",
      first_university: "Carrillo-Lewis",
      first_major: "Town planner",
      third_university: "Clark PLC",
      third_major: "Records manager",
    },
    totalPoints: 767,
    rank: 1,
  },
  {
    user: {
      full_name: "Jennifer Armstrong",
      highschool: "PLC",
      first_university: "Wilson, Horton and Hudson",
      first_major: "Charity fundraiser",
      second_university: "Fischer-Mejia",
    },
    totalPoints: 345,
    rank: 2,
  },
  {
    user: {
      full_name: "Daniel Monroe",
      highschool: "Ltd",
      first_university: "Long PLC",
      first_major: "Visual merchandiser",
      second_university: "Wood-Wright",
      second_major: "Engineer, aeronautical",
      third_university: "Smith-Johnson",
      third_major: "Engineer, aeronautical",
    },
    totalPoints: 548,
    rank: 3,
  },
  {
    user: {
      full_name: "Misty Knight",
      highschool: "Inc",
      first_university: "Burke-Arnold",
      first_major: "Solicitor",
      third_major: "Surveyor, rural practice",
    },
    totalPoints: 80,
    rank: 4,
  },
  {
    user: {
      full_name: "Bernard Nguyen",
      highschool: "and Sons",
      first_university: "Walker-Robertson",
      first_major: "Call centre manager",
      second_university: "Jones Ltd",
      third_university: "Wells and Sons",
    },
    totalPoints: 381,
    rank: 5,
  },
  {
    user: {
      full_name: "Victoria Robinson",
      highschool: "PLC",
      first_university: "Wells, Gates and Harris",
      first_major: "Energy engineer",
      second_university: "Hayes, Hernandez and Murray",
      third_major: "Chief Marketing Officer",
    },
    totalPoints: 280,
    rank: 6,
  },
  {
    user: {
      full_name: "Anna Campbell",
      highschool: "LLC",
      first_university: "Humphrey, Harris and Kim",
      first_major: "Museum education officer",
      second_university: "Mitchell, Aguirre and Miller",
      second_major: "Wellsite geologist",
      third_major: "Stage manager",
    },
    totalPoints: 759,
    rank: 7,
  },
  {
    user: {
      full_name: "Jodi Reeves",
      highschool: "LLC",
      first_university: "Lewis PLC",
      first_major: "Politician's assistant",
      second_university: "Johnson-Thomas",
      second_major: "Occupational psychologist",
    },
    totalPoints: 239,
    rank: 8,
  },
  {
    user: {
      full_name: "Emily Fowler",
      highschool: "Group",
      first_university: "Page, Landry and Curtis",
      choosen_major_one: "Loss adjuster, chartered",
      second_university: "Wolfe-Davis",
      second_major: "Radiation protection practitioner",
    },
    totalPoints: 110,
    rank: 9,
  },
  {
    user: {
      full_name: "Angela Patterson",
      highschool: "Inc",
      first_university: "Glover-Freeman",
      choosen_major_one: "Museum education officer",
      third_major: "Multimedia programmer",
    },
    totalPoints: 908,
    rank: 10,
  },
];
